package edu.brown.cs.checkers.client;

public enum MessageType {
	JOINGAME, STARTGAME, JOIN, CREATE, CHANGE, DESTROY, WINNER, 
	LOSER, HANDOUT_CARD, NO_CARDS_LEFT, PREVIOUS_ACTION, VALID_ACTIONS,
	ERROR, MOVE, MESSAGE, PLAYER_INFORMATION, PING, LEAVER, CRASH;

}
